### PR TITLE
Updated crypto libs

### PR DESCRIPTION
**Pull request by anti-social**

### CODE REVIEW

**Comment by anti-social** [comment]
It is curious that `sha2::Sha512Trunc256` produces different hash.

**Comment by anti-social** [comment]
I found out that initial state for `sha512/256` is different from `sha512`.

**Comment by anti-social** [comment]
`blake2b/256` is broken in this PR. We are waiting for RustCrypto/hashes/issues/28.

**Comment by tailhook** [comment]
This seems to be obsolete. I've imported a test from this patch, though.

**Pull request closed without merging**
